
services:
    lmssuggests_1:
        image: lmssuggests:latest
        container_name: suggests1_in_lms_network
        build:
            context: ..
            dockerfile: Dockerfile
        ports:
            - "8076:8080"
        environment:
            SPRING_PROFILES_ACTIVE: instance1,bootstrap
        networks:
            - lms_network
        volumes:
            - "uploaded_files_volume_1:/tmp"

    lmssuggests_2:
        image: lmssuggests:latest
        container_name: suggests2_in_lms_network
        build:
            context: ..
            dockerfile: Dockerfile
        ports:
            - "8077:8080"
        environment:
            SPRING_PROFILES_ACTIVE: instance2,bootstrap
        networks:
            - lms_network
        volumes:
            - "uploaded_files_volume_2:/tmp"

networks:
    lms_network:
        external: true

volumes:
    uploaded_files_volume_1:
    uploaded_files_volume_2: