@startuml
title As a reader, I want to suggest the acquisition of a new Book.

participant "Suggestion" as suggestion
participant "Book" as book
participant "Message Broker" as mb
note left of suggestion
  Nota: Os eventos de subscribe não estão descritos
end note
 -> suggestion: POST /suggest/isbn(with book details)
activate suggestion
suggestion -> suggestion: suggestBook(bookSuggestion)

activate mb
suggestion -> suggestion: save(bookSuggestion)
suggestion -> mb: publish{bookSuggestion}
<-- suggestion:  202 Accepted

mb -> suggestion: notify{bookSuggestion}

suggestion -> suggestion: Librarian analyze suggestion and accepts it

    suggestion -> mb: publish{"book.accepted"}
    mb -> book: Notify {book.accepted}
    activate book
    book -> book: createSuggestedBook(book)
    book -> mb: publish{book}
    mb -> book: notify{book}
    deactivate book


deactivate librarian

@enduml